export const highThoughts = [
  "Do pets name their owners?",
  "The number of people older than you never goes up.",
  "In order to fall asleep, we have to pretend to be asleep.",
  "If you clean a vacuum, do you become the vacuum cleaner?",
  "Your future self is watching you through memories.",
  "A different version of you exists in everyone who knows you.",
  "We call it a building even after the builders are finished.",
  "Every mirror is technically showing you the past.",
  "Nothing is on fire. Fire is on things.",
  "The first person to hear a parrot talk was probably not okay for a while.",
  "Your stomach thinks every potato is mashed.",
  "A calendar is just a really slow clock.",
  "You have never seen your own face—only reflections and pictures of it.",
  "Somewhere, somebody remembers a story about you that you have forgotten.",
  "Music is invisible furniture for the room you are in.",
] as const;

export const soberThoughts = [
  "The pool table leans left. Adjust your aim.",
  "Bartender's rule: cash rules the tray.",
  "Keep the jukebox feeding, kid.",
  "If the stool wobbles, fold a coaster twice.",
  "Never trust a clean ashtray after midnight.",
  "The back booth belongs to whoever got there first.",
  "Last call is a warning, not a negotiation.",
  "A good regular knows when not to ask what happened.",
  "Tip the bartender before you need a favor.",
  "The neon sign hums in B-flat. Probably.",
  "Rack your own table and mind the house cue.",
  "The jukebox remembers every bad decision in this room.",
] as const;
